language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

#coveralls support
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
  - pip install .
  - pip install -r requirements.txt

#tests
script:
  - pytest


after_success:
  - coveralls

#to run for selected versions:
#after_success:
#  - if [[ $ENV == python=3.4* ]]; then
#      coveralls;
#    fi